spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    # DriverManager automatically selects driver className since JDBC4 (SDK6)
  jpa:
    hibernate:
      ddl-auto: none # create, create-drop, validate, update, none; none allows app to load if db fails
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
