# src/main/resources/application.yml

app.name: BasicsApplication

# servers
server.servlet.context-path: /
server.servlet.port: 8080
server.error.whitelabel.enabled: false

# database
datasource.platform: h2
spring.datasource.url: jdbc:h2:mem:testdb
spring.h2.console.enabled: true
spring.h2.console.path: /h2console

# logging
spring.main.banner-mode: CONSOLE
spring.output.ansi.enabled: ALWAYS
logging.level.org.springframework: ERROR
