# src/main/resources/application.yml

app.name: BasicsApplication

# database
# note: persistence is case sensitive with objects; multilines need MultipleLinesSqlCommandExtractor
# note: H2 Console JDBC URL must match spring.datasource.url
datasource.platform: h2
spring.datasource.url: jdbc:h2:mem:testdb
spring.h2.console.enabled: true
spring.h2.console.path: /h2console
