# hibernate.properties
hibernate.connection.driver_class=oracle.jdbc.OracleDriver
hibernate.connection.url=jdbc:oracle:thin:@//localhost:1521/XE
#hibernate.connection.username=SYS as sysdba
#hibernate.connection.password=xxxxxx
hibernate.default_catalog=XE
hibernate.default_schema=SYSTEM
