# src/main/resources/application.yml
spring:

  application:
    name: EmbeddedApplication

  sql:
    init:
      mode: ALWAYS

  h2:
    console:
      enabled: true

  # only needed for DataSourceBuilder DB_CLOSE_ON_EXIT=FALSE
  datasource:
    #    jdbc:h2:mem:mydb;INIT=create schema if not exists mydb\;runscript from '~/import.sql'
    url: jdbc:h2:mem:mydb;mode=Oracle;
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2

  jpa:
#   show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        hbm2ddl:
          charset_name: UTF-8
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

# app.name: EmbeddedApplication
# database; persistence is case sensitive with objects
# multilines need MultipleLinesSqlCommandExtractor
# H2 Console JDBC URL must match spring.datasource.url
# spring.jpa.properties.hibernate.hbm2ddl.charset_name: UTF-8 > IMPACTS LOGGING OUTPUT !
