# src/main/resources/application.yml

app.name: TestmoreApplication

server.servlet.context-path: /
server.servlet.port: 8080

server.error.whitelabel.enabled: false

datasource.platform: h2

logging.level.org.springframework: ERROR

spring.main.banner-mode: CONSOLE
spring.output.ansi.enabled: ALWAYS
