spring:
  application:
    name: graphqlp

  datasource:
    # JPA required @Table( name = "cities", schema = "app")
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driverClassName: org.postgresql.Driver
    # driverClassName: org.apache.derby.jdbc.EmbeddedDriver, ClientDriver
    # DriverManager automatically selects driver className since JDBC4 (SDK6)

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      # ddl-auto:create, create-drop, validate, update, none; none allows app to load if db fails
      # dialect: org.hibernate.dialect.DerbyDialect, DerbyTenSevenDialect, PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true
