# src/main/resources/application.yml

app.name: WebFlux Samples

spring.thymeleaf.enabled=true: true

# database
datasource.platform: h2
spring.datasource.url: jdbc:h2:mem:testdb
spring.h2.console.enabled: true
spring.h2.console.path: /h2console

spring.datasource.maximum-pool-size: 100
