# src/main/resources/application.yml

app.name: BasicsApplication

# database
datasource.platform: h2
spring.datasource.url: jdbc:h2:mem:testdb
spring.h2.console.enabled: true
spring.h2.console.path: /h2console
