app.name: RdbmsApplication

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

# database
# persistence is case sensitive with objects
# embedded multilines need MultipleLinesSqlCommandExtractor
# embedded H2 Console JDBC URL must match spring.datasource.url
# embedded spring.jpa.properties.hibernate.hbm2ddl.charset_name: UTF-8 > IMPACTS LOGGING OUTPUT !
# embedded to rdbms means switching: gradle, app.props

# database embedded
#datasource.platform: h2
#spring.datasource.url: jdbc:h2:mem:history
#spring.datasource.platform: h2
#spring.h2.console.enabled: true
#spring.h2.console.path: /h2console

# database configs
#spring.datasource.sqlScriptEncoding: UTF-8
#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
#spring.jpa.properties.hibernate.hbm2ddl.charset_name: UTF-8

# mysql
#spring.jpa.show-sql: true
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
spring.datasource.username: ${MYSQL_USER}
spring.datasource.password: ${MYSQL_PASS}
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# actuators
management.security.enabled: false
management.endpoints.web.exposure.include: info, health, env, beans, metrics, configprops, conditions, logfile, sessions, auditevents, shutdown
management.endpoints.web.base-path: /actuator
spring.jackson.serialization.indent_output: true
#management.port: 9000
#management.endpoints.shutdown.enabled: true

# additional configs
spring.http.encoding.charset: UTF-8
#spring.http.encoding.enabled: true
#spring.http.encoding.force: true
