# https://docs.spring.io/spring-boot/appendix/application-properties/index.html
spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testdb
server.port=8080
users.api.url=http://localhost:${server.port}/api
